# -*- coding: utf-8 -*-
"""Multibandit_Taks2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9Ebh6Nmc_p026DWI7V1s1BB7EYpt3wz
"""

import numpy as np

class EpsilonGreedy:
    def __init__(self, n_arms, epsilon):
        self.n_arms = n_arms
        self.epsilon = epsilon
        self.counts = np.zeros(n_arms)
        self.values = np.zeros(n_arms)

    def select_arm(self):
        if np.random.rand() < self.epsilon:
            return np.random.randint(0, self.n_arms)
        else:
            return np.argmax(self.values)

    def update(self, chosen_arm, reward):
        self.counts[chosen_arm] += 1
        n = self.counts[chosen_arm]
        value = self.values[chosen_arm]
        self.values[chosen_arm] = ((n - 1) / n) * value + (1 / n) * reward


n_arms = 10
epsilon = 0.1
n_trials = 5000

true_means = np.random.randn(n_arms)
print(f"Actual mean rewards for each arm: {np.round(true_means, 2)}")
print(
    f"The best arm is #{np.argmax(true_means)} with a mean of {np.max(true_means):.2f}\n")

agent = EpsilonGreedy(n_arms, epsilon)
total_reward = 0

for t in range(n_trials):
    arm_to_pull = agent.select_arm()
    reward = np.random.randn() + true_means[arm_to_pull]
    agent.update(arm_to_pull, reward)
    total_reward += reward

print(f"Total Reward: {total_reward:.2f}")

class UCB:
    def __init__(self, n_arms):
        self.n_arms = n_arms
        self.counts = np.zeros(n_arms)
        self.values = np.zeros(n_arms)
        self.total_counts = 0

    def select_arm(self):
        # For the first few trials, if an arm has not been pulled,
        # its UCB value might be very high due to the log(total_counts + 1) / (counts + 1e-5) term.
        # To handle initial exploration, we can pull unpulled arms first.
        for arm_idx in range(self.n_arms):
            if self.counts[arm_idx] == 0:
                return arm_idx
        ucb_values = self.values + np.sqrt(2 * np.log(self.total_counts) / self.counts)
        return np.argmax(ucb_values)

    def update(self, chosen_arm, reward):
        self.counts[chosen_arm] += 1
        self.total_counts += 1
        n = self.counts[chosen_arm]
        value = self.values[chosen_arm]
        self.values[chosen_arm] = ((n - 1) / n) * value + (1 / n) * reward

# Example usage
agent = UCB(n_arms)
total_reward = 0

for t in range(n_trials):
    arm = agent.select_arm()
    # Generate reward based on true_means, similar to the EpsilonGreedy example
    reward = np.random.randn() + true_means[arm]
    agent.update(arm, reward)
    total_reward += reward

print("Total Reward:", total_reward)

class ThompsonSampling:
    def __init__(self, n_arms):
        self.n_arms = n_arms
        self.successes = np.zeros(n_arms)
        self.failures = np.zeros(n_arms)

    def select_arm(self):
        sampled_values = np.random.beta(self.successes + 1, self.failures + 1)
        return np.argmax(sampled_values)

    def update(self, chosen_arm, reward):
        # For Thompson Sampling with a Beta-Bernoulli prior,
        # rewards are typically binary (0 or 1).
        # However, if 'reward' is a continuous value (as in our multi-armed bandit setup),
        # we need to decide what constitutes a 'success' or 'failure'.
        # A common approach is to consider a positive reward as a 'success'.
        if reward > 0:
            self.successes[chosen_arm] += 1
        else:
            self.failures[chosen_arm] += 1

# Example usage
agent = ThompsonSampling(n_arms)
total_reward = 0

for t in range(n_trials):
    arm = agent.select_arm()
    # Generate reward based on true_means, similar to the EpsilonGreedy example
    reward = np.random.randn() + true_means[arm]
    agent.update(arm, reward)
    total_reward += reward

print("Total Reward:", total_reward)

